import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { UserProvider } from '@/context/UserContext';
import { BookmarkProvider } from '@/context/BookmarkContext';
import { ThemeProvider } from '@/context/ThemeContext';
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "hrDashboard",
  description: "Generated by create next app",
};



export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <ThemeProvider>
          <UserProvider>
            <BookmarkProvider>
              {children}
            </BookmarkProvider>
          </UserProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
