import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { UserProvider } from '@/context/UserContext';
import { BookmarkProvider } from '@/context/BookmarkContext';
import { ThemeProvider } from '@/context/ThemeContext';
import Navbar from "@/components/ui/navbar";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "hrDashboard",
  description: "Generated by create next app",
};


export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="bg-amber-50">
        <ThemeProvider>
          <UserProvider>
            <BookmarkProvider>
              <Navbar/>
              <main className="p-4  max-w-7xl  mx-auto">{children}</main>
            </BookmarkProvider>
          </UserProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
